workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      java:
        version: 11
      ndk: 25c
    triggering:
      events:
        - push
      branch:
        - main
    scripts:
      - name: Set up build
        script: |
          cd $FCI_BUILD_DIR
          python3 -m pip install --upgrade pip
          python3 -m pip install buildozer Cython
      - name: Build APK
        script: |
          cd $FCI_BUILD_DIR
          buildozer android release
    artifacts:
      - bin/*.apk
      - bin/*.aab
    publishing:
      email:
        recipients:
          - $CODEMAGIC_EMAIL
        notify:
          success: true
          failure: true
